[project]
name = "src"
version = "0.0.2"
description = "An MLOps project for productionizing models"
authors = [{name = "Nam Nguyen", email = "namtktn1@gmail.com"}]

[tool.setuptools]
packages = {find = {}}

[tool.setuptools.dynamic]
dependencies = {file = "requirements.txt"}